name: Toggle maintenance mode

on:
  workflow_dispatch:
    inputs:
      mode:
        description: Choose which site to publish
        required: true
        type: choice
        options:
          - enable
          - disable

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  publish:
    name: ${{ inputs.mode == 'enable' && 'Enable' || 'Disable' }} maintenance mode
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /maintenance/
            /public/

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6

      - name: Upload maintenance site
        if: inputs.mode == 'enable'
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: maintenance

      - name: Upload live site
        if: inputs.mode == 'disable'
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: public

      - name: Publish selected site
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
